<?xml version="1.0"?>
<package format="3">
  <name>mobile_base_gazebo</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic simulation for the modular mecanum mobile base.</description>
  <maintainer email="safwan@example.com">Safwan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
